### ISSUE TITLE
Prepare for Milestone 1 Release

### ISSUE THREAD

**Issue by IrinaSouth** [featurehub-io/featurehub#191]
Focus is on support for percentage rollout in UI, server side full rollout strategy implementations for most SDKs.

- [x] e2e test session 
- [x]  Update docs:  
docs.featurehub.io 
New section: 
- Rollout strategies 
 -- Percentage rollout 
      ---Description of the percentage rollout functionality. Any limitations. 
      ---Simple example / use case of when it can be used  
    
- [x] Update examples - Typescript - UI
- [x] Update examples - Typescript -backend
- [x] Update examples - Java-backend
- [x] Update examples -  C#
- [x] Update examples - Dart 
- [x] Update examples - Flutter

- [x] Video example - React app updating. - [x] Update video links, add new video demonstration 

- [x]  Build new docker containers

- [x]  Update release notes 

- [x]  Release new NPM, Java, Dart, C# SDK modules  

- [x]  Update docs in the main readmes
featurehub repo index readme

- [x]  Update screenshots on the website

- [x] Update website to include rollout strategies feature 

- [x] Update Demo site
- [x] Review npm typescript SDK docs
