### ISSUE TITLE
STRATEGY: Add % rollout support

### ISSUE THREAD

**Issue by IrinaSouth** [featurehub-io/featurehub#68]
Add  % rollout support to enhance A/B testing. 

- [x] Should sum up to 100%

- [x] Percentage field should not allow greater than 100% when adding new strategy

- [x] Do we need to display warning messages when something doesn't sum up?

- [x] If string, number, json strategy is not set - it should show as "not set" on collapsed view

- [x] Check different user permissions reflected correctly

- [x] Fix choice chips

- [x] Fix overflow issues when columns have multiple strategies

- [x] Rounding is broken when entering percentage value. E.g. 0.0005 defaults to 0

- [x] Can't go back to "not set" after value is set for strings, numbers, json

@rvowles
